baseURL = "https://pajakbalikpapan.github.io/"
languageCode = "en-us"
title = "Layanan Pajak"
theme = "kube"
description = "Melayani kebutuhan anda terhadap pemenuhan kewajiban perpajakan untuk lebih patuh dan tertib perpajakan"
pagination = 10
author ="La Ode Adam Saputra"
[build]
  writeStats = true

[params]
  noindex_kinds = [
    "taxonomy",
    "taxonomyTerm"
  ]

[Params.seo.webmaster_verifications]
  google = "UA-176078354-1" # Optional, Google verification code

[taxonomies]
  category = "categories"

[[menu.main]]
    name = "Kontak"
    weight = -100
    url = "/contact/"